version: "3"

services:
  dallas:
    build:
      context: .
      args:
        SECRET_KEY: ${SECRET_KEY}
    env_file: .env
    volumes:
      - ./:/opt/webapp
    ports:
      - "8000:${PORT}"
  postgres:
    environment:
      POSTGRES_PASSWORD: <postgres_pwd>
      PGDATA: /var/lib/postgresql/data/dallas
    volumes:
      - postgres-data:/var/lib/postgresql/data/dallas
    ports:
      - "5432:5432"
  redis:
    ports:
      - "6379:6379"

volumes: 
  postgres-data:

